cities = [
  { id: 263, name: "Kabupaten Aceh Barat Daya", province_id: 21 },
  { id: 264, name: "Kabupaten Aceh Besar", province_id: 21 },
  { id: 265, name: "Kabupaten Aceh Jaya", province_id: 21 },
  { id: 266, name: "Kabupaten Aceh Selatan", province_id: 21 },
  { id: 267, name: "Kabupaten Aceh Singkil", province_id: 21 },
  { id: 268, name: "Kabupaten Aceh Tamiang", province_id: 21 },
  { id: 269, name: "Kabupaten Aceh Tengah", province_id: 21 },
  { id: 270, name: "Kabupaten Aceh Tenggara", province_id: 21 },
  { id: 271, name: "Kabupaten Aceh Timur", province_id: 21 },
  { id: 272, name: "Kabupaten Aceh Utara", province_id: 21 },
  { id: 446, name: "Kabupaten Agam", province_id: 32 },
  { id: 295, name: "Kabupaten Alor", province_id: 23 },
  { id: 482, name: "Kabupaten Asahan", province_id: 34 },
  { id: 317, name: "Kabupaten Asmat", province_id: 24 },
  { id: 1, name: "Kabupaten Badung", province_id: 1 },
  { id: 177, name: "Kabupaten Balangan", province_id: 13 },
  { id: 64, name: "Kabupaten Bandung", province_id: 9 },
  { id: 65, name: "Kabupaten Bandung Barat", province_id: 9 },
  { id: 401, name: "Kabupaten Banggai", province_id: 29 },
  { id: 402, name: "Kabupaten Banggai Kepulauan", province_id: 29 },
  { id: 403, name: "Kabupaten Banggai Laut", province_id: 29 },
  { id: 10, name: "Kabupaten Bangka", province_id: 2 },
  { id: 11, name: "Kabupaten Bangka Barat", province_id: 2 },
  { id: 12, name: "Kabupaten Bangka Selatan", province_id: 2 },
  { id: 13, name: "Kabupaten Bangka Tengah", province_id: 2 },
  { id: 125, name: "Kabupaten Bangkalan", province_id: 11 },
  { id: 2, name: "Kabupaten Bangli", province_id: 1 },
  { id: 178, name: "Kabupaten Banjar", province_id: 13 },
  { id: 90, name: "Kabupaten Banjarnegara", province_id: 10 },
  { id: 377, name: "Kabupaten Bantaeng", province_id: 28 },
  { id: 35, name: "Kabupaten Bantul", province_id: 5 },
  { id: 465, name: "Kabupaten Banyuasin", province_id: 33 },
  { id: 91, name: "Kabupaten Banyumas", province_id: 10 },
  { id: 126, name: "Kabupaten Banyuwangi", province_id: 11 },
  { id: 181, name: "Kabupaten Barito Kuala", province_id: 13 },
  { id: 190, name: "Kabupaten Barito Selatan", province_id: 14 },
  { id: 191, name: "Kabupaten Barito Timur", province_id: 14 },
  { id: 192, name: "Kabupaten Barito Utara", province_id: 14 },
  { id: 378, name: "Kabupaten Barru", province_id: 28 },
  { id: 92, name: "Kabupaten Batang", province_id: 10 },
  { id: 52, name: "Kabupaten Batang Hari", province_id: 8 },
  { id: 483, name: "Kabupaten Batu Bara", province_id: 34 },
  { id: 68, name: "Kabupaten Bekasi", province_id: 9 },
  { id: 14, name: "Kabupaten Belitung", province_id: 2 },
  { id: 15, name: "Kabupaten Belitung Timur", province_id: 2 },
  { id: 296, name: "Kabupaten Belu", province_id: 23 },
  { id: 274, name: "Kabupaten Bener Meriah", province_id: 21 },
  { id: 359, name: "Kabupaten Bengkalis", province_id: 26 },
  { id: 163, name: "Kabupaten Bengkayang", province_id: 12 },
  { id: 26, name: "Kabupaten Bengkulu Selatan", province_id: 4 },
  { id: 27, name: "Kabupaten Bengkulu Tengah", province_id: 4 },
  { id: 28, name: "Kabupaten Bengkulu Utara", province_id: 4 },
  { id: 205, name: "Kabupaten Berau", province_id: 15 },
  { id: 318, name: "Kabupaten Biak Numfor", province_id: 24 },
  { id: 285, name: "Kabupaten Bima", province_id: 22 },
  { id: 220, name: "Kabupaten Bintan", province_id: 17 },
  { id: 275, name: "Kabupaten Bireuen", province_id: 21 },
  { id: 129, name: "Kabupaten Blitar", province_id: 11 },
  { id: 93, name: "Kabupaten Blora", province_id: 10 },
  { id: 46, name: "Kabupaten Boalemo", province_id: 7 },
  { id: 69, name: "Kabupaten Bogor", province_id: 9 },
  { id: 130, name: "Kabupaten Bojonegoro", province_id: 11 },
  { id: 432, name: "Kabupaten Bolaang Mongondow", province_id: 31 },
  { id: 433, name: "Kabupaten Bolaang Mongondow Selatan", province_id: 31 },
  { id: 434, name: "Kabupaten Bolaang Mongondow Timur", province_id: 31 },
  { id: 435, name: "Kabupaten Bolaang Mongondow Utara", province_id: 31 },
  { id: 415, name: "Kabupaten Bombana", province_id: 30 },
  { id: 131, name: "Kabupaten Bondowoso", province_id: 11 },
  { id: 379, name: "Kabupaten Bone", province_id: 28 },
  { id: 47, name: "Kabupaten Bone Bolango", province_id: 7 },
  { id: 319, name: "Kabupaten Boven Digoel", province_id: 24 },
  { id: 94, name: "Kabupaten Boyolali", province_id: 10 },
  { id: 95, name: "Kabupaten Brebes", province_id: 10 },
  { id: 3, name: "Kabupaten Buleleng", province_id: 1 },
  { id: 380, name: "Kabupaten Bulukumba", province_id: 28 },
  { id: 214, name: "Kabupaten Bulungan", province_id: 16 },
  { id: 53, name: "Kabupaten Bungo", province_id: 8 },
  { id: 404, name: "Kabupaten Buol", province_id: 29 },
  { id: 242, name: "Kabupaten Buru", province_id: 19 },
  { id: 243, name: "Kabupaten Buru Selatan", province_id: 19 },
  { id: 416, name: "Kabupaten Buton", province_id: 30 },
  { id: 417, name: "Kabupaten Buton Selatan", province_id: 30 },
  { id: 418, name: "Kabupaten Buton Tengah", province_id: 30 },
  { id: 419, name: "Kabupaten Buton Utara", province_id: 30 },
  { id: 71, name: "Kabupaten Ciamis", province_id: 9 },
  { id: 72, name: "Kabupaten Cianjur", province_id: 9 },
  { id: 96, name: "Kabupaten Cilacap", province_id: 10 },
  { id: 75, name: "Kabupaten Cirebon", province_id: 9 },
  { id: 485, name: "Kabupaten Dairi", province_id: 34 },
  { id: 320, name: "Kabupaten Deiyai", province_id: 24 },
  { id: 486, name: "Kabupaten Deli Serdang", province_id: 34 },
  { id: 97, name: "Kabupaten Demak", province_id: 10 },
  { id: 448, name: "Kabupaten Dharmasraya", province_id: 32 },
  { id: 321, name: "Kabupaten Dogiyai", province_id: 24 },
  { id: 287, name: "Kabupaten Dompu", province_id: 22 },
  { id: 405, name: "Kabupaten Donggala", province_id: 29 },
  { id: 466, name: "Kabupaten Empat Lawang", province_id: 33 },
  { id: 297, name: "Kabupaten Ende", province_id: 23 },
  { id: 381, name: "Kabupaten Enrekang", province_id: 28 },
  { id: 346, name: "Kabupaten Fakfak", province_id: 25 },
  { id: 298, name: "Kabupaten Flores Timur", province_id: 23 },
  { id: 77, name: "Kabupaten Garut", province_id: 9 },
  { id: 276, name: "Kabupaten Gayo Lues", province_id: 21 },
  { id: 5, name: "Kabupaten Gianyar", province_id: 1 },
  { id: 49, name: "Kabupaten Gorontalo", province_id: 7 },
  { id: 50, name: "Kabupaten Gorontalo Utara", province_id: 7 },
  { id: 382, name: "Kabupaten Gowa", province_id: 28 },
  { id: 132, name: "Kabupaten Gresik", province_id: 11 },
  { id: 98, name: "Kabupaten Grobogan", province_id: 10 },
  { id: 36, name: "Kabupaten Gunung Kidul", province_id: 5 },
  { id: 193, name: "Kabupaten Gunung Mas", province_id: 14 },
  { id: 252, name: "Kabupaten Halmahera Barat", province_id: 20 },
  { id: 253, name: "Kabupaten Halmahera Selatan", province_id: 20 },
  { id: 254, name: "Kabupaten Halmahera Tengah", province_id: 20 },
  { id: 255, name: "Kabupaten Halmahera Timur", province_id: 20 },
  { id: 256, name: "Kabupaten Halmahera Utara", province_id: 20 },
  { id: 182, name: "Kabupaten Hulu Sungai Selatan", province_id: 13 },
  { id: 183, name: "Kabupaten Hulu Sungai Tengah", province_id: 13 },
  { id: 184, name: "Kabupaten Hulu Sungai Utara", province_id: 13 },
  { id: 488, name: "Kabupaten Humbang Hasundutan", province_id: 34 },
  { id: 361, name: "Kabupaten Indragiri Hilir", province_id: 26 },
  { id: 362, name: "Kabupaten Indragiri Hulu", province_id: 26 },
  { id: 78, name: "Kabupaten Indramayu", province_id: 9 },
  { id: 322, name: "Kabupaten Intan Jaya", province_id: 24 },
  { id: 324, name: "Kabupaten Jayapura", province_id: 24 },
  { id: 325, name: "Kabupaten Jayawijaya", province_id: 24 },
  { id: 133, name: "Kabupaten Jember", province_id: 11 },
  { id: 6, name: "Kabupaten Jembrana", province_id: 1 },
  { id: 383, name: "Kabupaten Jeneponto", province_id: 28 },
  { id: 99, name: "Kabupaten Jepara", province_id: 10 },
  { id: 134, name: "Kabupaten Jombang", province_id: 11 },
  { id: 347, name: "Kabupaten Kaimana", province_id: 25 },
  { id: 363, name: "Kabupaten Kampar", province_id: 26 },
  { id: 194, name: "Kabupaten Kapuas", province_id: 14 },
  { id: 164, name: "Kabupaten Kapuas Hulu", province_id: 12 },
  { id: 100, name: "Kabupaten Karanganyar", province_id: 10 },
  { id: 7, name: "Kabupaten Karangasem", province_id: 1 },
  { id: 79, name: "Kabupaten Karawang", province_id: 9 },
  { id: 221, name: "Kabupaten Karimun", province_id: 17 },
  { id: 489, name: "Kabupaten Karo", province_id: 34 },
  { id: 195, name: "Kabupaten Katingan", province_id: 14 },
  { id: 29, name: "Kabupaten Kaur", province_id: 4 },
  { id: 165, name: "Kabupaten Kayong Utara", province_id: 12 },
  { id: 101, name: "Kabupaten Kebumen", province_id: 10 },
  { id: 136, name: "Kabupaten Kediri", province_id: 11 },
  { id: 326, name: "Kabupaten Keerom", province_id: 24 },
  { id: 102, name: "Kabupaten Kendal", province_id: 10 },
  { id: 30, name: "Kabupaten Kepahiang", province_id: 4 },
  { id: 222, name: "Kabupaten Kepulauan Anambas", province_id: 17 },
  { id: 244, name: "Kabupaten Kepulauan Aru", province_id: 19 },
  { id: 449, name: "Kabupaten Kepulauan Mentawai", province_id: 32 },
  { id: 364, name: "Kabupaten Kepulauan Meranti", province_id: 26 },
  { id: 436, name: "Kabupaten Kepulauan Sangihe", province_id: 31 },
  { id: 384, name: "Kabupaten Kepulauan Selayar", province_id: 28 },
  { id: 45, name: "Kabupaten Kepulauan Seribu", province_id: 6 },
  { id: 437, name: "Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)", province_id: 31 },
  { id: 257, name: "Kabupaten Kepulauan Sula", province_id: 20 },
  { id: 438, name: "Kabupaten Kepulauan Talaud", province_id: 31 },
  { id: 327, name: "Kabupaten Kepulauan Yapen", province_id: 24 },
  { id: 55, name: "Kabupaten Kerinci", province_id: 8 },
  { id: 166, name: "Kabupaten Ketapang", province_id: 12 },
  { id: 103, name: "Kabupaten Klaten", province_id: 10 },
  { id: 8, name: "Kabupaten Klungkung", province_id: 1 },
  { id: 421, name: "Kabupaten Kolaka", province_id: 30 },
  { id: 422, name: "Kabupaten Kolaka Timur", province_id: 30 },
  { id: 423, name: "Kabupaten Kolaka Utara", province_id: 30 },
  { id: 424, name: "Kabupaten Konawe", province_id: 30 },
  { id: 425, name: "Kabupaten Konawe Kepulauan", province_id: 30 },
  { id: 426, name: "Kabupaten Konawe Selatan", province_id: 30 },
  { id: 427, name: "Kabupaten Konawe Utara", province_id: 30 },
  { id: 185, name: "Kabupaten Kotabaru", province_id: 13 },
  { id: 196, name: "Kabupaten Kotawaringin Barat", province_id: 14 },
  { id: 197, name: "Kabupaten Kotawaringin Timur", province_id: 14 },
  { id: 365, name: "Kabupaten Kuantan Singingi", province_id: 26 },
  { id: 167, name: "Kabupaten Kubu Raya", province_id: 12 },
  { id: 104, name: "Kabupaten Kudus", province_id: 10 },
  { id: 37, name: "Kabupaten Kulon Progo", province_id: 5 },
  { id: 80, name: "Kabupaten Kuningan", province_id: 9 },
  { id: 300, name: "Kabupaten Kupang", province_id: 23 },
  { id: 207, name: "Kabupaten Kutai Barat", province_id: 15 },
  { id: 208, name: "Kabupaten Kutai Kartanegara", province_id: 15 },
  { id: 209, name: "Kabupaten Kutai Timur", province_id: 15 },
  { id: 490, name: "Kabupaten Labuhanbatu", province_id: 34 },
  { id: 491, name: "Kabupaten Labuhanbatu Selatan", province_id: 34 },
  { id: 492, name: "Kabupaten Labuhanbatu Utara", province_id: 34 },
  { id: 467, name: "Kabupaten Lahat", province_id: 33 },
  { id: 198, name: "Kabupaten Lamandau", province_id: 14 },
  { id: 137, name: "Kabupaten Lamongan", province_id: 11 },
  { id: 227, name: "Kabupaten Lampung Barat", province_id: 18 },
  { id: 228, name: "Kabupaten Lampung Selatan", province_id: 18 },
  { id: 229, name: "Kabupaten Lampung Tengah", province_id: 18 },
  { id: 230, name: "Kabupaten Lampung Timur", province_id: 18 },
  { id: 231, name: "Kabupaten Lampung Utara", province_id: 18 },
  { id: 168, name: "Kabupaten Landak", province_id: 12 },
  { id: 493, name: "Kabupaten Langkat", province_id: 34 },
  { id: 328, name: "Kabupaten Lanny Jaya", province_id: 24 },
  { id: 18, name: "Kabupaten Lebak", province_id: 3 },
  { id: 31, name: "Kabupaten Lebong", province_id: 4 },
  { id: 301, name: "Kabupaten Lembata", province_id: 23 },
  { id: 450, name: "Kabupaten Lima Puluh Kota", province_id: 32 },
  { id: 223, name: "Kabupaten Lingga", province_id: 17 },
  { id: 288, name: "Kabupaten Lombok Barat", province_id: 22 },
  { id: 289, name: "Kabupaten Lombok Tengah", province_id: 22 },
  { id: 290, name: "Kabupaten Lombok Timur", province_id: 22 },
  { id: 291, name: "Kabupaten Lombok Utara", province_id: 22 },
  { id: 138, name: "Kabupaten Lumajang", province_id: 11 },
  { id: 385, name: "Kabupaten Luwu", province_id: 28 },
  { id: 386, name: "Kabupaten Luwu Timur", province_id: 28 },
  { id: 387, name: "Kabupaten Luwu Utara", province_id: 28 },
  { id: 140, name: "Kabupaten Madiun", province_id: 11 },
  { id: 106, name: "Kabupaten Magelang", province_id: 10 },
  { id: 141, name: "Kabupaten Magetan", province_id: 11 },
  { id: 210, name: "Kabupaten Mahakam Ulu", province_id: 15 },
  { id: 81, name: "Kabupaten Majalengka", province_id: 9 },
  { id: 371, name: "Kabupaten Majene", province_id: 27 },
  { id: 302, name: "Kabupaten Malaka", province_id: 23 },
  { id: 143, name: "Kabupaten Malang", province_id: 11 },
  { id: 215, name: "Kabupaten Malinau", province_id: 16 },
  { id: 245, name: "Kabupaten Maluku Barat Daya", province_id: 19 },
  { id: 246, name: "Kabupaten Maluku Tengah", province_id: 19 },
  { id: 247, name: "Kabupaten Maluku Tenggara", province_id: 19 },
  { id: 248, name: "Kabupaten Maluku Tenggara Barat", province_id: 19 },
  { id: 372, name: "Kabupaten Mamasa", province_id: 27 },
  { id: 329, name: "Kabupaten Mamberamo Raya", province_id: 24 },
  { id: 330, name: "Kabupaten Mamberamo Tengah", province_id: 24 },
  { id: 373, name: "Kabupaten Mamuju", province_id: 27 },
  { id: 374, name: "Kabupaten Mamuju Tengah", province_id: 27 },
  { id: 375, name: "Kabupaten Mamuju Utara", province_id: 27 },
  { id: 494, name: "Kabupaten Mandailing Natal", province_id: 34 },
  { id: 303, name: "Kabupaten Manggarai", province_id: 23 },
  { id: 304, name: "Kabupaten Manggarai Barat", province_id: 23 },
  { id: 305, name: "Kabupaten Manggarai Timur", province_id: 23 },
  { id: 348, name: "Kabupaten Manokwari", province_id: 25 },
  { id: 349, name: "Kabupaten Manokwari Selatan", province_id: 25 },
  { id: 331, name: "Kabupaten Mappi", province_id: 24 },
  { id: 389, name: "Kabupaten Maros", province_id: 28 },
  { id: 350, name: "Kabupaten Maybrat", province_id: 25 },
  { id: 169, name: "Kabupaten Melawi", province_id: 12 },
  { id: 170, name: "Kabupaten Mempawah", province_id: 12 },
  { id: 56, name: "Kabupaten Merangin", province_id: 8 },
  { id: 332, name: "Kabupaten Merauke", province_id: 24 },
  { id: 232, name: "Kabupaten Mesuji", province_id: 18 },
  { id: 333, name: "Kabupaten Mimika", province_id: 24 },
  { id: 441, name: "Kabupaten Minahasa", province_id: 31 },
  { id: 442, name: "Kabupaten Minahasa Selatan", province_id: 31 },
  { id: 443, name: "Kabupaten Minahasa Tenggara", province_id: 31 },
  { id: 444, name: "Kabupaten Minahasa Utara", province_id: 31 },
  { id: 145, name: "Kabupaten Mojokerto", province_id: 11 },
  { id: 406, name: "Kabupaten Morowali", province_id: 29 },
  { id: 407, name: "Kabupaten Morowali Utara", province_id: 29 },
  { id: 469, name: "Kabupaten Muara Enim", province_id: 33 },
  { id: 57, name: "Kabupaten Muaro Jambi", province_id: 8 },
  { id: 32, name: "Kabupaten Muko Muko", province_id: 4 },
  { id: 428, name: "Kabupaten Muna", province_id: 30 },
  { id: 429, name: "Kabupaten Muna Barat", province_id: 30 },
  { id: 199, name: "Kabupaten Murung Raya", province_id: 14 },
  { id: 470, name: "Kabupaten Musi Banyuasin", province_id: 33 },
  { id: 471, name: "Kabupaten Musi Rawas", province_id: 33 },
  { id: 472, name: "Kabupaten Musi Rawas Utara", province_id: 33 },
  { id: 334, name: "Kabupaten Nabire", province_id: 24 },
  { id: 279, name: "Kabupaten Nagan Raya", province_id: 21 },
  { id: 306, name: "Kabupaten Nagekeo", province_id: 23 },
  { id: 224, name: "Kabupaten Natuna", province_id: 17 },
  { id: 335, name: "Kabupaten Nduga", province_id: 24 },
  { id: 307, name: "Kabupaten Ngada", province_id: 23 },
  { id: 146, name: "Kabupaten Nganjuk", province_id: 11 },
  { id: 147, name: "Kabupaten Ngawi", province_id: 11 },
  { id: 496, name: "Kabupaten Nias", province_id: 34 },
  { id: 497, name: "Kabupaten Nias Barat", province_id: 34 },
  { id: 498, name: "Kabupaten Nias Selatan", province_id: 34 },
  { id: 499, name: "Kabupaten Nias Utara", province_id: 34 },
  { id: 216, name: "Kabupaten Nunukan", province_id: 16 },
  { id: 473, name: "Kabupaten Ogan Ilir", province_id: 33 },
  { id: 474, name: "Kabupaten Ogan Komering Ilir", province_id: 33 },
  { id: 475, name: "Kabupaten Ogan Komering Ulu", province_id: 33 },
  { id: 476, name: "Kabupaten Ogan Komering Ulu Selatan", province_id: 33 },
  { id: 477, name: "Kabupaten Ogan Komering Ulu Timur", province_id: 33 },
  { id: 148, name: "Kabupaten Pacitan", province_id: 11 },
  { id: 500, name: "Kabupaten Padang Lawas", province_id: 34 },
  { id: 501, name: "Kabupaten Padang Lawas Utara", province_id: 34 },
  { id: 453, name: "Kabupaten Padang Pariaman", province_id: 32 },
  { id: 503, name: "Kabupaten Pakpak Bharat", province_id: 34 },
  { id: 149, name: "Kabupaten Pamekasan", province_id: 11 },
  { id: 19, name: "Kabupaten Pandeglang", province_id: 3 },
  { id: 82, name: "Kabupaten Pangandaran", province_id: 9 },
  { id: 391, name: "Kabupaten Pangkajene Kepulauan", province_id: 28 },
  { id: 336, name: "Kabupaten Paniai", province_id: 24 },
  { id: 409, name: "Kabupaten Parigi Moutong", province_id: 29 },
  { id: 455, name: "Kabupaten Pasaman", province_id: 32 },
  { id: 456, name: "Kabupaten Pasaman Barat", province_id: 32 },
  { id: 211, name: "Kabupaten Paser", province_id: 15 },
  { id: 151, name: "Kabupaten Pasuruan", province_id: 11 },
  { id: 107, name: "Kabupaten Pati", province_id: 10 },
  { id: 351, name: "Kabupaten Pegunungan Arfak", province_id: 25 },
  { id: 337, name: "Kabupaten Pegunungan Bintang", province_id: 24 },
  { id: 109, name: "Kabupaten Pekalongan", province_id: 10 },
  { id: 367, name: "Kabupaten Pelalawan", province_id: 26 },
  { id: 110, name: "Kabupaten Pemalang", province_id: 10 },
  { id: 212, name: "Kabupaten Penajam Paser Utara", province_id: 15 },
  { id: 480, name: "Kabupaten Penukal Abab Lematang Ilir", province_id: 33 },
  { id: 234, name: "Kabupaten Pesawaran", province_id: 18 },
  { id: 235, name: "Kabupaten Pesisir Barat", province_id: 18 },
  { id: 458, name: "Kabupaten Pesisir Selatan", province_id: 32 },
  { id: 280, name: "Kabupaten Pidie", province_id: 21 },
  { id: 281, name: "Kabupaten Pidie Jaya", province_id: 21 },
  { id: 393, name: "Kabupaten Pinrang", province_id: 28 },
  { id: 51, name: "Kabupaten Pohuwato", province_id: 7 },
  { id: 376, name: "Kabupaten Polewali Mandar", province_id: 27 },
  { id: 152, name: "Kabupaten Ponorogo", province_id: 11 },
  { id: 410, name: "Kabupaten Poso", province_id: 29 },
  { id: 236, name: "Kabupaten Pringsewu", province_id: 18 },
  { id: 154, name: "Kabupaten Probolinggo", province_id: 11 },
  { id: 201, name: "Kabupaten Pulang Pisau", province_id: 14 },
  { id: 258, name: "Kabupaten Pulau Morotai", province_id: 20 },
  { id: 259, name: "Kabupaten Pulau Taliabu", province_id: 20 },
  { id: 338, name: "Kabupaten Puncak", province_id: 24 },
  { id: 339, name: "Kabupaten Puncak Jaya", province_id: 24 },
  { id: 111, name: "Kabupaten Purbalingga", province_id: 10 },
  { id: 83, name: "Kabupaten Purwakarta", province_id: 9 },
  { id: 112, name: "Kabupaten Purworejo", province_id: 10 },
  { id: 352, name: "Kabupaten Raja Ampat", province_id: 25 },
  { id: 33, name: "Kabupaten Rejang Lebong", province_id: 4 },
  { id: 113, name: "Kabupaten Rembang", province_id: 10 },
  { id: 368, name: "Kabupaten Rokan Hilir", province_id: 26 },
  { id: 369, name: "Kabupaten Rokan Hulu", province_id: 26 },
  { id: 308, name: "Kabupaten Rote Ndao", province_id: 23 },
  { id: 309, name: "Kabupaten Sabu Raijua", province_id: 23 },
  { id: 172, name: "Kabupaten Sambas", province_id: 12 },
  { id: 505, name: "Kabupaten Samosir", province_id: 34 },
  { id: 155, name: "Kabupaten Sampang", province_id: 11 },
  { id: 173, name: "Kabupaten Sanggau", province_id: 12 },
  { id: 340, name: "Kabupaten Sarmi", province_id: 24 },
  { id: 58, name: "Kabupaten Sarolangun", province_id: 8 },
  { id: 174, name: "Kabupaten Sekadau", province_id: 12 },
  { id: 34, name: "Kabupaten Seluma", province_id: 4 },
  { id: 116, name: "Kabupaten Semarang", province_id: 10 },
  { id: 249, name: "Kabupaten Seram Bagian Barat", province_id: 19 },
  { id: 250, name: "Kabupaten Seram Bagian Timur", province_id: 19 },
  { id: 21, name: "Kabupaten Serang", province_id: 3 },
  { id: 506, name: "Kabupaten Serdang Bedagai", province_id: 34 },
  { id: 202, name: "Kabupaten Seruyan", province_id: 14 },
  { id: 370, name: "Kabupaten Siak", province_id: 26 },
  { id: 394, name: "Kabupaten Sidenreng Rappang", province_id: 28 },
  { id: 156, name: "Kabupaten Sidoarjo", province_id: 11 },
  { id: 411, name: "Kabupaten Sigi", province_id: 29 },
  { id: 460, name: "Kabupaten Sijunjung", province_id: 32 },
  { id: 310, name: "Kabupaten Sikka", province_id: 23 },
  { id: 508, name: "Kabupaten Simalungun", province_id: 34 },
  { id: 283, name: "Kabupaten Simeulue", province_id: 21 },
  { id: 395, name: "Kabupaten Sinjai", province_id: 28 },
  { id: 176, name: "Kabupaten Sintang", province_id: 12 },
  { id: 157, name: "Kabupaten Situbondo", province_id: 11 },
  { id: 38, name: "Kabupaten Sleman", province_id: 5 },
  { id: 462, name: "Kabupaten Solok", province_id: 32 },
  { id: 463, name: "Kabupaten Solok Selatan", province_id: 32 },
  { id: 396, name: "Kabupaten Soppeng", province_id: 28 },
  { id: 354, name: "Kabupaten Sorong", province_id: 25 },
  { id: 355, name: "Kabupaten Sorong Selatan", province_id: 25 },
  { id: 117, name: "Kabupaten Sragen", province_id: 10 },
  { id: 84, name: "Kabupaten Subang", province_id: 9 },
  { id: 86, name: "Kabupaten Sukabumi", province_id: 9 },
  { id: 203, name: "Kabupaten Sukamara", province_id: 14 },
  { id: 118, name: "Kabupaten Sukoharjo", province_id: 10 },
  { id: 311, name: "Kabupaten Sumba Barat", province_id: 23 },
  { id: 312, name: "Kabupaten Sumba Barat Daya", province_id: 23 },
  { id: 313, name: "Kabupaten Sumba Tengah", province_id: 23 },
  { id: 314, name: "Kabupaten Sumba Timur", province_id: 23 },
  { id: 293, name: "Kabupaten Sumbawa", province_id: 22 },
  { id: 294, name: "Kabupaten Sumbawa Barat", province_id: 22 },
  { id: 87, name: "Kabupaten Sumedang", province_id: 9 },
  { id: 158, name: "Kabupaten Sumenep", province_id: 11 },
  { id: 341, name: "Kabupaten Supiori", province_id: 24 },
  { id: 186, name: "Kabupaten Tabalong", province_id: 13 },
  { id: 9, name: "Kabupaten Tabanan", province_id: 1 },
  { id: 397, name: "Kabupaten Takalar", province_id: 28 },
  { id: 356, name: "Kabupaten Tambrauw", province_id: 25 },
  { id: 217, name: "Kabupaten Tana Tidung", province_id: 16 },
  { id: 398, name: "Kabupaten Tana Toraja", province_id: 28 },
  { id: 187, name: "Kabupaten Tanah Bumbu", province_id: 13 },
  { id: 464, name: "Kabupaten Tanah Datar", province_id: 32 },
  { id: 188, name: "Kabupaten Tanah Laut", province_id: 13 },
  { id: 23, name: "Kabupaten Tangerang", province_id: 3 },
  { id: 237, name: "Kabupaten Tanggamus", province_id: 18 },
  { id: 60, name: "Kabupaten Tanjung Jabung Barat", province_id: 8 },
  { id: 61, name: "Kabupaten Tanjung Jabung Timur", province_id: 8 },
  { id: 510, name: "Kabupaten Tapanuli Selatan", province_id: 34 },
  { id: 511, name: "Kabupaten Tapanuli Tengah", province_id: 34 },
  { id: 512, name: "Kabupaten Tapanuli Utara", province_id: 34 },
  { id: 189, name: "Kabupaten Tapin", province_id: 13 },
  { id: 88, name: "Kabupaten Tasikmalaya", province_id: 9 },
  { id: 62, name: "Kabupaten Tebo", province_id: 8 },
  { id: 121, name: "Kabupaten Tegal", province_id: 10 },
  { id: 357, name: "Kabupaten Teluk Bintuni", province_id: 25 },
  { id: 358, name: "Kabupaten Teluk Wondama", province_id: 25 },
  { id: 122, name: "Kabupaten Temanggung", province_id: 10 },
  { id: 315, name: "Kabupaten Timor Tengah Selatan", province_id: 23 },
  { id: 316, name: "Kabupaten Timor Tengah Utara", province_id: 23 },
  { id: 514, name: "Kabupaten Toba Samosir", province_id: 34 },
  { id: 412, name: "Kabupaten Tojo Una-Una", province_id: 29 },
  { id: 413, name: "Kabupaten Toli-Toli", province_id: 29 },
  { id: 342, name: "Kabupaten Tolikara", province_id: 24 },
  { id: 399, name: "Kabupaten Toraja Utara", province_id: 28 },
  { id: 160, name: "Kabupaten Trenggalek", province_id: 11 },
  { id: 161, name: "Kabupaten Tuban", province_id: 11 },
  { id: 238, name: "Kabupaten Tulang Bawang", province_id: 18 },
  { id: 239, name: "Kabupaten Tulang Bawang Barat", province_id: 18 },
  { id: 162, name: "Kabupaten Tulungagung", province_id: 11 },
  { id: 400, name: "Kabupaten Wajo", province_id: 28 },
  { id: 430, name: "Kabupaten Wakatobi", province_id: 30 },
  { id: 343, name: "Kabupaten Waropen", province_id: 24 },
  { id: 240, name: "Kabupaten Way Kanan", province_id: 18 },
  { id: 123, name: "Kabupaten Wonogiri", province_id: 10 },
  { id: 124, name: "Kabupaten Wonosobo", province_id: 10 },
  { id: 344, name: "Kabupaten Yahukimo", province_id: 24 },
  { id: 345, name: "Kabupaten Yalimo", province_id: 24 },
  { id: 241, name: "Kota Ambon", province_id: 19 },
  { id: 204, name: "Kota Balikpapan", province_id: 15 },
  { id: 273, name: "Kota Banda Aceh", province_id: 21 },
  { id: 226, name: "Kota Bandar Lampung", province_id: 18 },
  { id: 63, name: "Kota Bandung", province_id: 9 },
  { id: 66, name: "Kota Banjar", province_id: 9 },
  { id: 179, name: "Kota Banjarbaru", province_id: 13 },
  { id: 180, name: "Kota Banjarmasin", province_id: 13 },
  { id: 219, name: "Kota Batam", province_id: 17 },
  { id: 127, name: "Kota Batu", province_id: 11 },
  { id: 414, name: "Kota Bau-Bau", province_id: 30 },
  { id: 67, name: "Kota Bekasi", province_id: 9 },
  { id: 25, name: "Kota Bengkulu", province_id: 4 },
  { id: 286, name: "Kota Bima", province_id: 22 },
  { id: 484, name: "Kota Binjai", province_id: 34 },
  { id: 431, name: "Kota Bitung", province_id: 31 },
  { id: 128, name: "Kota Blitar", province_id: 11 },
  { id: 70, name: "Kota Bogor", province_id: 9 },
  { id: 206, name: "Kota Bontang", province_id: 15 },
  { id: 447, name: "Kota Bukittinggi", province_id: 32 },
  { id: 17, name: "Kota Cilegon", province_id: 3 },
  { id: 73, name: "Kota Cimahi", province_id: 9 },
  { id: 74, name: "Kota Cirebon", province_id: 9 },
  { id: 4, name: "Kota Denpasar", province_id: 1 },
  { id: 76, name: "Kota Depok", province_id: 9 },
  { id: 360, name: "Kota Dumai", province_id: 26 },
  { id: 48, name: "Kota Gorontalo", province_id: 7 },
  { id: 487, name: "Kota Gunungsitoli", province_id: 34 },
  { id: 40, name: "Kota Jakarta Barat", province_id: 6 },
  { id: 41, name: "Kota Jakarta Pusat", province_id: 6 },
  { id: 42, name: "Kota Jakarta Selatan", province_id: 6 },
  { id: 43, name: "Kota Jakarta Timur", province_id: 6 },
  { id: 44, name: "Kota Jakarta Utara", province_id: 6 },
  { id: 54, name: "Kota Jambi", province_id: 8 },
  { id: 323, name: "Kota Jayapura", province_id: 24 },
  { id: 135, name: "Kota Kediri", province_id: 11 },
  { id: 420, name: "Kota Kendari", province_id: 30 },
  { id: 439, name: "Kota Kotamobagu", province_id: 31 },
  { id: 299, name: "Kota Kupang", province_id: 23 },
  { id: 277, name: "Kota Langsa", province_id: 21 },
  { id: 278, name: "Kota Lhokseumawe", province_id: 21 },
  { id: 468, name: "Kota Lubuk Linggau", province_id: 33 },
  { id: 139, name: "Kota Madiun", province_id: 11 },
  { id: 105, name: "Kota Magelang", province_id: 10 },
  { id: 388, name: "Kota Makassar", province_id: 28 },
  { id: 142, name: "Kota Malang", province_id: 11 },
  { id: 440, name: "Kota Manado", province_id: 31 },
  { id: 292, name: "Kota Mataram", province_id: 22 },
  { id: 495, name: "Kota Medan", province_id: 34 },
  { id: 233, name: "Kota Metro", province_id: 18 },
  { id: 144, name: "Kota Mojokerto", province_id: 11 },
  { id: 451, name: "Kota Padang", province_id: 32 },
  { id: 452, name: "Kota Padang Panjang", province_id: 32 },
  { id: 502, name: "Kota Padang Sidempuan", province_id: 34 },
  { id: 478, name: "Kota Pagar Alam", province_id: 33 },
  { id: 200, name: "Kota Palangka Raya", province_id: 14 },
  { id: 479, name: "Kota Palembang", province_id: 33 },
  { id: 390, name: "Kota Palopo", province_id: 28 },
  { id: 408, name: "Kota Palu", province_id: 29 },
  { id: 16, name: "Kota Pangkal Pinang", province_id: 2 },
  { id: 392, name: "Kota Parepare", province_id: 28 },
  { id: 454, name: "Kota Pariaman", province_id: 32 },
  { id: 150, name: "Kota Pasuruan", province_id: 11 },
  { id: 457, name: "Kota Payakumbuh", province_id: 32 },
  { id: 108, name: "Kota Pekalongan", province_id: 10 },
  { id: 366, name: "Kota Pekanbaru", province_id: 26 },
  { id: 504, name: "Kota Pematang Siantar", province_id: 34 },
  { id: 171, name: "Kota Pontianak", province_id: 12 },
  { id: 481, name: "Kota Prabumulih", province_id: 33 },
  { id: 153, name: "Kota Probolinggo", province_id: 11 },
  { id: 282, name: "Kota Sabang", province_id: 21 },
  { id: 114, name: "Kota Salatiga", province_id: 10 },
  { id: 213, name: "Kota Samarinda", province_id: 15 },
  { id: 459, name: "Kota Sawah Lunto", province_id: 32 },
  { id: 115, name: "Kota Semarang", province_id: 10 },
  { id: 20, name: "Kota Serang", province_id: 3 },
  { id: 507, name: "Kota Sibolga", province_id: 34 },
  { id: 175, name: "Kota Singkawang", province_id: 12 },
  { id: 461, name: "Kota Solok", province_id: 32 },
  { id: 353, name: "Kota Sorong", province_id: 25 },
  { id: 284, name: "Kota Subulussalam", province_id: 21 },
  { id: 85, name: "Kota Sukabumi", province_id: 9 },
  { id: 59, name: "Kota Sungaipenuh", province_id: 8 },
  { id: 159, name: "Kota Surabaya", province_id: 11 },
  { id: 119, name: "Kota Surakarta", province_id: 10 },
  { id: 22, name: "Kota Tangerang", province_id: 3 },
  { id: 24, name: "Kota Tangerang Selatan", province_id: 3 },
  { id: 509, name: "Kota Tanjung Balai", province_id: 34 },
  { id: 225, name: "Kota Tanjung Pinang", province_id: 17 },
  { id: 218, name: "Kota Tarakan", province_id: 16 },
  { id: 89, name: "Kota Tasikmalaya", province_id: 9 },
  { id: 513, name: "Kota Tebing Tinggi", province_id: 34 },
  { id: 120, name: "Kota Tegal", province_id: 10 },
  { id: 260, name: "Kota Ternate", province_id: 20 },
  { id: 261, name: "Kota Tidore Kepulauan", province_id: 20 },
  { id: 445, name: "Kota Tomohon", province_id: 31 },
  { id: 251, name: "Kota Tual", province_id: 19 },
  { id: 39, name: "Kota Yogyakarta", province_id: 5 },

]

cities.each do |data|
  City.find_or_create_by(id: data[:id]) do |city|
    city.id = data[:id]
    city.name = data[:name]
    city.province_id = data[:province_id]
    city.save
  end
end
puts "=== City seeding done ... ==="
