development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: dropbox_development

test:
  adapter: test

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: redis://api.smartdropbox.online:6379/1
  channel_prefix: dropbox_production
